### ISSUE TITLE
Not working with BGB 1.5.2

### ISSUE THREAD

**Issue by coczero** [Spiraster/LiveSplit.OoA#1]
I can't seem to get the AutoSplitter to work with BGB 1.5.2. It works without problems with Gambatte.

**Comment by Spiraster** [comment]
Make sure that you only have one instance of BGB and/or Gambatte open at once. The autosplitter will attach to the first process of either that it finds, and it may not be the one you want if there are multiple.

If that's not your issue, I'll take a look at what else it might be.

**Comment by coczero** [comment]
I tried BGB first, without even having Gambatte. Then tried Gambatte and that worked. BGB seems to be the better emulator, so I'd appreciate it if you would take a look :) Thanks!

**Comment by Spiraster** [comment]
So I'm fairly sure that the issue was bad pointers that weren't working in all circumstances. I've just replaced this component with a new script over [here](https://github.com/Spiraster/ASLScripts/tree/master/Oracles).

The new script doesn't rely on pointers at all and should be much more reliable.
